### ISSUE TITLE
Data type error

### ISSUE THREAD

**Issue by vinhthoai** [Thachj-Thw/emulator#1]
https://github.com/Thachj-Thw/emulator/blob/ee8c64d63c0c8de3d4832c88f86ada5b6eba0404/emulator/em_object.py#L43
I think in self._index + "xml". self._index must be of the form str. Otherwise it will cause string concatenation error

**Comment by Aris-NBTN** [comment]
Có cách nào để khi tạo mới tab giải lập thì nó tự động bật gỡ lỗi adb và root luôn không
Is there a way to automatically enable adb and root debugging when creating a new emulator tab?

**Comment by vinhthoai** [comment]
> Có cách nào để khi tạo mới tab giải lập thì nó tự động bật gỡ lỗi adb và root luôn không Is there a way to automatically enable adb and root debugging when creating a new emulator tab?

edit file E:\LDPlayer\LDPlayer9\vms\config\leidian{number}.config 
number is index ldplayer
"basicSettings.adbDebug": 0 --> "basicSettings.adbDebug": 1
