### ISSUE TITLE
Không dump được xml

### ISSUE THREAD

**Issue by Congdanh1997** [Thachj-Thw/emulator#2]
Traceback (most recent call last):
  File "C:\Users\Danh\PycharmProjects\Test_keo\Demo_emu\demo.py", line 7, in <module>
    em.find_node(By.TEXT, "Log in")
  File "C:\Users\Danh\PycharmProjects\Test_keo\venv\lib\site-packages\emulator\em_object.py", line 398, in find_node
    with open(self._dump, mode="r", encoding="utf-8") as file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Danh\\PycharmProjects\\Test_keo\\venv\\Lib\\site-packages\\emulator\\dump'

khi dùng dump_xml cũng không có file được xuất ra mong được bác hỗ trợ telegram @onepiece99997777

**Comment by Thachj-Thw** [comment]
Do phiên bản LDPlayer9 output một số lệnh ADB thay đổi và một số lệnh không hoạt động nên một vài method cũ bị lỗi. Mình đã fix lại để có thể chạy được trên LDPlayer9 và các phiên bản cũ hơn.
Bạn chạy lệnh **pip install --upgrade emulator-thw** để cập nhập lên phiên bản mới nhất là 0.0.9

**Comment by Thachj-Thw** [comment]
> Traceback (most recent call last): File "C:\Users\Danh\PycharmProjects\Test_keo\Demo_emu\demo.py", line 7, in em.find_node(By.TEXT, "Log in") File "C:\Users\Danh\PycharmProjects\Test_keo\venv\lib\site-packages\emulator\em_object.py", line 398, in find_node with open(self._dump, mode="r", encoding="utf-8") as file: PermissionError: [Errno 13] Permission denied: 'C:\Users\Danh\PycharmProjects\Test_keo\venv\Lib\site-packages\emulator\dump'
> 
> khi dùng dump_xml cũng không có file được xuất ra mong được bác hỗ trợ telegram @onepiece99997777

Do phiên bản LDPlayer9 output một số lệnh ADB thay đổi và một số lệnh không hoạt động nên một vài method cũ bị lỗi. Mình đã fix lại để có thể chạy được trên LDPlayer9 và các phiên bản cũ hơn.
Bạn chạy lệnh "**pip install --upgrade emulator-thw**" để cập nhập lên phiên bản mới nhất là 0.0.9
