### ISSUE TITLE
Đã cài thư viện nhưng không import được "emulator"

### ISSUE THREAD

**Issue by truongquocloc** [Thachj-Thw/emulator#4]
![lỗi](https://github.com/Thachj-Thw/emulator/assets/14223702/c3f555a1-3c7d-47cc-ad96-1f95e67d8870)

**Comment by Thachj-Thw** [comment]
> ![lỗi](https://private-user-images.githubusercontent.com/14223702/291337757-c3f555a1-3c7d-47cc-ad96-1f95e67d8870.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTYxMjAsIm5iZiI6MTcwMjk5NTgyMCwicGF0aCI6Ii8xNDIyMzcwMi8yOTEzMzc3NTctYzNmNTU1YTEtM2M3ZC00N2NjLWFkOTYtMWY5NWU2N2Q4ODcwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE0MjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGVmNzg4ODllZmU1ODM1MjkxY2NjNThjYjM4M2E0M2E0N2I4MzEwMmYwNmQ3NjAwMzljMTNhZTJmNmIxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yj2AxmbISxPIa1OiUxBW0OXpD9gD1ymBsOpUqKu93E)

bạn chụp lệnh install xem

**Comment by truongquocloc** [comment]
mình cài được r nha
