### ISSUE TITLE
Lỗi không xóa được LDplayer

### ISSUE THREAD

**Issue by truongquocloc** [Thachj-Thw/emulator#5]
Khi thực hiện lệnh 
em_remove = ld.emulators[0]
ld.remove(em_remove)
thì nó báo như này ạ
![errordelete](https://github.com/Thachj-Thw/emulator/assets/14223702/8929c8aa-5c92-4516-82af-73ab894ceb0a)

**Comment by Thachj-Thw** [comment]
Mình Fix rồi đó. upgrade lên bản 0.0.11 là được
