### ISSUE TITLE
Function start() not working correctly

### ISSUE THREAD

**Issue by truongquocloc** [Thachj-Thw/emulator#8]
Tôi code bằng visual studio code( vscode). đoạn code dưới đây khi chạy trong vscode thì bình thường, nhưng khi tôi dùng thư viện pyinstaller để xuất thành file cài đặt .exe thì run lại bị lỗi, mặc dù máy ảo vẫn lên nhưng output lại khác nhau. 

```
mport emulator
ld = emulator.LDPlayer("C:\\LDPlayer9\\LDPlayer9").emulators[0]
try: 
  ld.start(wait=True)
  f = open("demofile2.txt", "a")
  f.write("LDplayer start success")
  f.close()
except Exception as err:
  f = open("demofile2.txt", "a")
  f.write(f"LDplayer start error: {err}")
  f.close()
```

-Output khi chạy trong vscode: "LDplayer start success"
-Output khi chạy file exe: LDplayer start error: list index out of range

Mong tác giả sớm có phản hồi, mình đã mất nhiều thời gian để fix nhưng không được

**Comment by truongquocloc** [comment]
Mong tác giả sớm fix ạ

**Comment by truongquocloc** [comment]
Đây là cách mình fix lỗi này
![image](https://github.com/Thachj-Thw/emulator/assets/14223702/e426d409-0a77-44b4-9cdb-a8df6335dc2e)

Lỗi phát sinh ở khúc khai báo sed. Mình chia làm 2 trường hợp: môi trường thực thi, và môi trường dev

Kèm theo copy các file trong thư mục sed bỏ chung vào thư mục có file .exe mà mình vừa tạo bằng thư viện pyinstaller
![image](https://github.com/Thachj-Thw/emulator/assets/14223702/f695f32a-09f0-40be-8045-9a6de5c54e34)

**Comment by Thachj-Thw** [comment]
> Đây là cách mình fix lỗi này
> ![image](https://github.com/Thachj-Thw/emulator/assets/14223702/e426d409-0a77-44b4-9cdb-a8df6335dc2e)
> 
> Lỗi phát sinh ở khúc khai báo sed. Mình chia làm 2 trường hợp: môi trường thực thi, và môi trường dev
> 
> Kèm theo copy các file trong thư mục sed bỏ chung vào thư mục có file .exe mà mình vừa tạo bằng thư viện pyinstaller
> ![image](https://github.com/Thachj-Thw/emulator/assets/14223702/f695f32a-09f0-40be-8045-9a6de5c54e34)
> 
Hoặc bạn có thể thêm --add-data="path/to/folder/emulator/sed;emulator/sed" vào câu lệnh pyinstaller

**Comment by truongquocloc** [comment]
Thanks tác giả
